class Constants:
    """
    A class to hold constant values used throughout the application.
    """
    DOC_CERTIFICATE = "https://developers.bancointer.com.br/v4/docs/onde-obter-o-certificado"

    URL_BANKING = "/banking/v2"
    URL_BANKING_BALANCE = f"{URL_BANKING}/saldo"
    URL_TOKEN = "/oauth/v2/token"
    URL_BANKING_STATEMENT = f"{URL_BANKING}/extrato"
    URL_BANKING_ENRICHED_STATEMENT = f"{URL_BANKING_STATEMENT}/completo"
    URL_BANKING_STATEMENT_PDF = f"{URL_BANKING_STATEMENT}/exportar"
    URL_BANKING_PAYMENT = f"{URL_BANKING}/pagamento"
    URL_BANKING_PAYMENT_DARF = f"{URL_BANKING_PAYMENT}/darf"
    URL_BANKING_PAYMENT_BATCH = f"{URL_BANKING_PAYMENT}/lote"
    URL_BANKING_PAYMENT_PIX = f"{URL_BANKING}/pix"
    URL_BANKING_WEBHOOK = f"{URL_BANKING}/webhooks"

    URL_PIX = "/pix/v2"
    URL_PIX_PIX = f"{URL_PIX}/pix"
    URL_PIX_LOCATIONS = f"{URL_PIX}/loc"
    URL_PIX_IMMEDIATE_BILLINGS = f"{URL_PIX}/cob"
    URL_PIX_SCHEDULED_BILLINGS = f"{URL_PIX}/cobv"
    URL_PIX_SCHEDULED_BILLINGS_BATCH = f"{URL_PIX}/lotecobv"
    URL_PIX_WEBHOOK = f"{URL_PIX}/webhook"
    URL_PIX_WEBHOOK_CALLBACKS = f"{URL_PIX_WEBHOOK}/callbacks"

    URL_BILLING = "/cobranca/v3/cobrancas"
    URL_BILLING_SUMMARY = f"{URL_BILLING}/sumario"
    URL_BILLING_WEBHOOK = f"{URL_BILLING}/webhook"
    URL_BILLING_WEBHOOK_CALLBACKS = f"{URL_BILLING_WEBHOOK}/callbacks"

    BILLET_BILLING_READ_SCOPE = "boleto-cobranca.read"
    BILLET_BILLING_WRITE_SCOPE = "boleto-cobranca.write"
    READ_BALANCE_SCOPE = "extrato.read"
    BILLET_PAYMENT_READ_SCOPE = "pagamento-boleto.read"
    BILLET_PAYMENT_WRITE_SCOPE = "pagamento-boleto.write"
    DARF_PAYMENT_WRITE_SCOPE = "pagamento-darf.write"
    BATCH_PAYMENT_READ_SCOPE = "pagamento-lote.read"
    BATCH_PAYMENT_WRITE_SCOPE = "pagamento-lote.write"
    PIX_PAYMENT_WRITE_SCOPE = "pagamento-pix.write"
    PIX_PAYMENT_READ_SCOPE = "pagamento-pix.read"
    WEBHOOK_BANKING_READ_SCOPE = "webhook-banking.read"
    WEBHOOK_BANKING_WRITE_SCOPE = "webhook-banking.write"
    PIX_IMMEDIATE_BILLING_READ_SCOPE = "cob.read"
    PIX_IMMEDIATE_BILLING_WRITE_SCOPE = "cob.write"
    PIX_SCHEDULED_BILLING_READ_SCOPE = "cobv.read"
    PIX_SCHEDULED_BILLING_WRITE_SCOPE = "cobv.write"
    PIX_SCHEDULED_BILLING_BATCH_WRITE_SCOPE = "lotecobv.write"
    PIX_SCHEDULED_BILLING_BATCH_READ_SCOPE = "lotecobv.read"
    PIX_READ_SCOPE = "pix.read"
    PIX_WRITE_SCOPE = "pix.write"
    PIX_LOCATION_READ_SCOPE = "payloadlocation.read"
    PIX_LOCATION_WRITE_SCOPE = "payloadlocation.write"
    PIX_WEBHOOK_READ_SCOPE = "webhook.read"
    PIX_WEBHOOK_WRITE_SCOPE = "webhook.write"

    DAYS_TO_EXPIRE = 30

    CERTIFICATE_EXCEPTION_MESSAGE = "Certificate error!"
    GENERIC_EXCEPTION_MESSAGE = "Error executing SDK!"